# -*- coding: utf-8 -*-
"""Actividad 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1enNqlWi2osU7kOW1ZiLlacDHEcB_WW5m
"""

# Actividad 02 — Construcción de Portafolios Óptimos
# Finanzas en R — Markowitz vs Simulación Monte Carlo



# Instalar y cargar librerías
# tidyverse: manipulación de datos (dplyr) y gráficos (ggplot2)
# quadprog: resuelve el problema de optimización de Markowitz
if (!require(tidyverse)) install.packages("tidyverse")
if (!require(quadprog)) install.packages("quadprog")
if (!require(corrplot)) install.packages("corrplot")
library(tidyverse)
library(quadprog)
library(corrplot)


# Cargar los datos
portafolio_retornos <- read_csv("/content/portafolioretornos.csv")

head(portafolio_retornos)
str(portafolio_retornos)



# 1.ANÁLISIS EXPLORATORIO (EDA)

#Estadística descriptiva por activo
# across(everything(), ...) aplica las mismas funciones a cada columna
# de activo de una sola vez, en vez de repetir el cálculo 5 veces.
stats_por_activo <- portafolio_retornos %>%
  select(-fecha) %>%
  summarise(across(everything(),
    list(
      media = ~mean(., na.rm = TRUE),
      sd    = ~sd(., na.rm = TRUE),
      min   = ~min(., na.rm = TRUE),
      max   = ~max(., na.rm = TRUE)
    ),
    .names = "{.col}_{.fn}"
  ))

print(stats_por_activo)


# Histogramas de retornos por activo
# pivot_longer() convierte las 5 columnas de activos en una sola columna
# "activo" + una columna "retorno": formato que ggplot necesita para
# poder separar los gráficos por activo con facet_wrap().
portafolio_retornos %>%
  select(-fecha) %>%
  pivot_longer(everything(), names_to = "activo", values_to = "retorno") %>%
  ggplot(aes(x = retorno, fill = activo)) +
  geom_histogram(alpha = 0.45, binwidth = 0.01) +
  facet_wrap(~activo, scales = "free") +
  theme_minimal() +
  labs(title = "Distribución de Retornos Mensuales (2013-2021)",
       x = "Retorno", y = "Frecuencia")


#Retornos mensuales en el tiempo
portafolio_retornos %>%
  mutate(fecha = as.Date(fecha)) %>%
  pivot_longer(-fecha, names_to = "activo", values_to = "retorno") %>%
  ggplot(aes(x = fecha, y = retorno, color = activo)) +
  geom_line(alpha = 0.7) +
  facet_wrap(~activo, scales = "free_y") +
  theme_minimal() +
  labs(title = "Retornos Mensuales en el Tiempo",
       x = "Fecha", y = "Retorno")


# Matriz de correlación y covarianza
retornos_matrix <- portafolio_retornos %>%
  select(-fecha) %>%
  as.matrix()

# cor(): mide qué tan juntos se mueven dos activos (entre -1 y 1).
# Sirve para diversificar activos poco correlacionados entre sí
# reducen el riesgo total del portafolio sin sacrificar retorno.
correlacion <- cor(retornos_matrix)
print(round(correlacion, 3))

corrplot(correlacion, method = "circle", type = "upper",
         title = "Matriz de Correlaciones entre Activos",
         mar = c(0, 0, 2, 0))

# cov(): mide cómo varían juntos dos activos
covarianza <- cov(retornos_matrix)
print(round(covarianza, 6))



#MARKOWITZ: FRONTERA EFICIENTE EXACTA


#Preparar los insumos
retornos_esperados <- colMeans(retornos_matrix)
cov_matrix <- cov(retornos_matrix)
tasa_libre_riesgo <- 0.02 / 12  # 2% anual expresado en base mensual


# Resolver la frontera eficiente con quadprog
# Markowitz busca, para cada nivel de retorno objetivo, los pesos "w"
# que minimizan la varianza del portafolio (w' * Σ * w), sujeto a:
#   1) los pesos suman 1: se invierte el 100% del capital
#   2) el retorno esperado = retorno objetivo
#   3) cada peso >= 0 : long-only, sin venta corta
# quadprog::solve.QP() resuelve exactamente este tipo de problema
# Se llama "programación cuadrática" porque la función a minimizar
# es cuadrática: w' * Σ * w).

n_activos <- ncol(retornos_matrix)
retornos_objetivo <- seq(0.08, 0.20, length.out = 50) / 12  # 8%-20% anual, en mensual

frontera_markowitz <- data.frame(
  retorno = numeric(length(retornos_objetivo)),
  volatilidad = numeric(length(retornos_objetivo))
)
pesos_frontera <- matrix(NA, nrow = length(retornos_objetivo), ncol = n_activos)

for (i in seq_along(retornos_objetivo)) {
  r_obj <- retornos_objetivo[i]

  # H y f definen la función objetivo de quadprog: minimizar 0.5*w'Hw + f'w
  # Como queremos minimizar w' * Σ * w, usamos H = 2*Σ (quadprog exige
  # ese factor 2 por cómo está planteada su fórmula interna).
  H <- 2 * cov_matrix
  f <- rep(0, n_activos)

  # A y b0 definen las restricciones:
  #   columna 1 -> suma de pesos = 1
  #   columna 2 -> retorno esperado del portafolio = r_obj
  #   columnas 3 en adelante -> cada peso >= 0
  A <- cbind(
    rep(1, n_activos),
    retornos_esperados,
    diag(n_activos)
  )
  b0 <- c(1, r_obj, rep(0, n_activos))

  # meq = 2 le indica a quadprog que las 2 primeras columnas de A son
  # restricciones de igualdad (=); el resto son de desigualdad (>=).
  resultado <- solve.QP(H, f, A, b0, meq = 2)
  w_opt <- resultado$solution

  # Volatilidad del portafolio = sqrt(w' * Σ * w).
  # Se anualiza con sqrt(12) porque los datos son mensuales: la
  # varianza escala de forma lineal con el tiempo (12 meses), y como
  # la desviación estándar es la raíz de la varianza, escala con
  # la raíz del tiempo (sqrt(12)), no con 12 directo.
  vol_opt <- sqrt(t(w_opt) %*% cov_matrix %*% w_opt) * sqrt(12)

  frontera_markowitz$retorno[i] <- r_obj * 12
  frontera_markowitz$volatilidad[i] <- vol_opt
  pesos_frontera[i, ] <- w_opt
}

# Sharpe ratio de cada punto: retorno por sobre la tasa libre de riesgo,
# dividido por la volatilidad -> "cuánto retorno se obtiene por cada
# unidad de riesgo que asumes".
frontera_markowitz$sharpe <- (frontera_markowitz$retorno - 0.02) / frontera_markowitz$volatilidad


# balance riesgo-retorno posible con estos 5 activos.
idx_tangente <- which.max(frontera_markowitz$sharpe)
portafolio_tangente <- frontera_markowitz[idx_tangente, ]
pesos_tangente <- pesos_frontera[idx_tangente, ]

print(portafolio_tangente)
cat("Pesos del portafolio tangente:\n")
print(round(setNames(pesos_tangente, colnames(retornos_matrix)), 3))


#Graficar la frontera eficiente
ggplot(frontera_markowitz, aes(x = volatilidad, y = retorno)) +
  geom_line(linewidth = 1.2, color = "darkred") +
  geom_point(data = portafolio_tangente, color = "red", size = 4) +
  theme_minimal() +
  labs(title = "Frontera Eficiente de Markowitz (Exacta)",
       x = "Volatilidad Anual", y = "Retorno Anual Esperado")



#3. SIMULACIÓN MONTE CARLO (VALIDACIÓN)


# Simular 10,000 portafolios aleatorios

set.seed(42)  # fija la semilla aleatoria -> resultados reproducibles
n_sims <- 10000

resultados_sim <- data.frame(
  retorno_anual = numeric(n_sims),
  volatilidad_anual = numeric(n_sims),
  sharpe_ratio = numeric(n_sims)
)
pesos_sim <- matrix(NA, nrow = n_sims, ncol = n_activos)

for (i in 1:n_sims) {
  # runif() genera pesos aleatorios positivos, al dividir por su suma
  # total, garantizamos que siempre sumen 1 (100% del capital, long-only).
  w <- runif(n_activos)
  w <- w / sum(w)

  ret_port <- sum(w * retornos_esperados) * 12
  vol_port <- sqrt(t(w) %*% cov_matrix %*% w) * sqrt(12)
  sharpe <- (ret_port - 0.02) / vol_port

  resultados_sim$retorno_anual[i] <- ret_port
  resultados_sim$volatilidad_anual[i] <- vol_port
  resultados_sim$sharpe_ratio[i] <- sharpe
  pesos_sim[i, ] <- w
}

idx_mejor <- which.max(resultados_sim$sharpe_ratio)
mejor_sim <- resultados_sim[idx_mejor, ]

print(mejor_sim)


#Graficar la nube de portafolios simulados
ggplot(resultados_sim, aes(x = volatilidad_anual, y = retorno_anual, color = sharpe_ratio)) +
  geom_point(alpha = 0.5, size = 1) +
  scale_color_viridis_c(direction = 1) +
  geom_point(data = mejor_sim, color = "red", size = 4, shape = 21, stroke = 2) +
  theme_minimal() +
  labs(title = "Frontera Eficiente Simulada (10,000 portafolios)",
       x = "Volatilidad Anual", y = "Retorno Anual Esperado",
       color = "Sharpe Ratio")



#4. COMPARACIÓN: SIMULACIÓN VS MARKOWITZ


#Gráfico overlay (nube + frontera exacta)
ggplot() +
  geom_point(data = resultados_sim,
             aes(x = volatilidad_anual, y = retorno_anual, color = sharpe_ratio),
             alpha = 0.4, size = 1) +
  geom_line(data = frontera_markowitz,
            aes(x = volatilidad, y = retorno),
            color = "red", linewidth = 1.5, linetype = "dashed") +
  geom_point(data = mejor_sim,
             color = "darkred", size = 4, shape = 21, stroke = 2) +
  geom_point(data = portafolio_tangente,
             color = "darkgreen", size = 4, shape = 23, stroke = 2) +
  scale_color_viridis_c(direction = 1) +
  theme_minimal() +
  labs(title = "Frontera Eficiente: Simulación (puntos) vs Markowitz (línea roja)",
       x = "Volatilidad Anual", y = "Retorno Anual Esperado",
       color = "Sharpe (Sim)")


# Calcular la brecha de optimización
# Mide qué tan lejos quedó el mejor portafolio simulado
# (punto rojo oscuro del gráfico) del portafolio tangente exacto de
# Markowitz (punto verde)
brecha_retorno <- abs(mejor_sim$retorno_anual - portafolio_tangente$retorno)
brecha_vol <- abs(mejor_sim$volatilidad_anual - portafolio_tangente$volatilidad)
brecha_sharpe <- abs(mejor_sim$sharpe_ratio - portafolio_tangente$sharpe)

cat("Brecha de optimización (Simulación vs Markowitz):\n")
cat("Retorno:", round(brecha_retorno, 4), "\n")
cat("Volatilidad:", round(brecha_vol, 4), "\n")
cat("Sharpe:", round(brecha_sharpe, 4), "\n")
cat("Error relativo en Sharpe:",
    round(brecha_sharpe / portafolio_tangente$sharpe * 100, 2), "%\n")